[workspace]
members = [
    "packages/vesting-base",
]

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true

[workspace.dependencies]
cosmwasm-schema = { version = "2.2.2", default-features = false }
cosmwasm-std = { version = "2.2.2", default-features = false, features = ["std", "iterator"] }
cw-storage-plus = { version = "2.0.0", default-features = false, features = ["iterator"] }
cw-utils = { version = "2.0.0", default-features = false }
cw20 = { version = "2.0.0", default-features = false }
thiserror = "1.0.49"
